apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-docker-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: test-docker
  template:
    metadata:
      labels:
        app: test-docker
    spec:
      containers:
      - name: test-docker-container
        image: elascano2/espedockers:latest
        image: rgguerrero/test_docker:latest
        ports:
        - containerPort: 5000
